const fs = require('fs');

// Read English recipes
const enRecipes = JSON.parse(fs.readFileSync('src/locales/en/recipes.json', 'utf8'));
const svRecipes = JSON.parse(fs.readFileSync('src/locales/sv/recipes.json', 'utf8'));

console.log('🇸🇪 Starting Swedish translation...');
console.log('');

// Translation mappings for common terms
const translations = {
  // Cooking methods
  'fried': 'stekt',
  'grilled': 'grillad',
  'baked': 'bakad',
  'steamed': 'ångad',
  'boiled': 'kokt',
  'stir-fried': 'wokad',
  'braised': 'bräserad',
  'roasted': 'rostad',
  'simmered': 'sjuden',
  'marinated': 'marinerad',
  'slow-cooked': 'långkokt',
  'pan-fried': 'stekt i panna',
  'deep-fried': 'friterad',
  
  // Difficulty levels
  'Easy': 'Lätt',
  'Medium': 'Medel',
  'Hard': 'Svår',
  
  // Common ingredients
  'chicken': 'kyckling',
  'beef': 'nötkött',
  'pork': 'fläskkött',
  'lamb': 'lammkött',
  'fish': 'fisk',
  'shrimp': 'räkor',
  'eggs': 'ägg',
  'rice': 'ris',
  'noodles': 'nudlar',
  'pasta': 'pasta',
  'bread': 'bröd',
  'cheese': 'ost',
  'milk': 'mjölk',
  'cream': 'grädde',
  'butter': 'smör',
  'oil': 'olja',
  'salt': 'salt',
  'pepper': 'peppar',
  'garlic': 'vitlök',
  'onion': 'lök',
  'tomato': 'tomat',
  'potato': 'potatis',
  'carrot': 'morot',
  'lettuce': 'sallad',
  'cucumber': 'gurka',
  'bell pepper': 'paprika',
  'mushroom': 'svamp',
  'ginger': 'ingefära',
  'lemon': 'citron',
  'lime': 'lime',
  'orange': 'apelsin',
  'apple': 'äpple',
  'banana': 'banan',
  'flour': 'mjöl',
  'sugar': 'socker',
  'honey': 'honung',
  'vinegar': 'vinäger',
  'soy sauce': 'sojasås',
  'olive oil': 'olivolja',
  'sesame oil': 'sesamolja',
  'coconut milk': 'kokosmjölk',
  'yogurt': 'yoghurt',
  'tofu': 'tofu',
  'beans': 'bönor',
  'peanuts': 'jordnötter',
  'almonds': 'mandlar',
  'walnuts': 'valnötter',
  'herbs': 'kryddor',
  'spices': 'kryddor',
  'basil': 'basilika',
  'oregano': 'oregano',
  'thyme': 'timjan',
  'cilantro': 'koriander',
  'parsley': 'persilja',
  'mint': 'mynta',
  'dill': 'dill',
  'rosemary': 'rosmarin',
  'sage': 'salvia',
  'bay leaves': 'lagerblad',
  'cinnamon': 'kanel',
  'nutmeg': 'muskotnöt',
  'cloves': 'nejlikor',
  'cardamom': 'kardemumma',
  'cumin': 'spiskummin',
  'coriander': 'koriander',
  'paprika': 'paprika',
  'chili powder': 'chilipulver',
  'black pepper': 'svartpeppar',
  'white pepper': 'vitpeppar',
  'red pepper': 'röd paprika',
  'green pepper': 'grön paprika',
  'jalapeño': 'jalapeño',
  'chili': 'chili',
  'curry': 'curry',
  'turmeric': 'gurkmeja',
  'ginger': 'ingefära',
  'garlic': 'vitlök',
  'shallot': 'schalottenlök',
  'scallion': 'salladslök',
  'leek': 'purjolök',
  'fennel': 'fänkål',
  'celery': 'selleri',
  'spinach': 'spenat',
  'kale': 'grönkål',
  'arugula': 'ruccola',
  'watercress': 'krasse',
  'radish': 'rädisa',
  'turnip': 'kålrot',
  'beet': 'rödbeta',
  'sweet potato': 'sötpotatis',
  'yam': 'jams',
  'corn': 'majs',
  'peas': 'ärtor',
  'green beans': 'bönor',
  'asparagus': 'sparris',
  'broccoli': 'broccoli',
  'cauliflower': 'blomkål',
  'cabbage': 'kål',
  'brussels sprouts': 'brysselkål',
  'artichoke': 'kronärtskocka',
  'eggplant': 'aubergine',
  'zucchini': 'zucchini',
  'squash': 'pumpa',
  'pumpkin': 'pumpa',
  'avocado': 'avokado',
  'olives': 'oliver',
  'capers': 'kapris',
  'anchovies': 'ansjovis',
  'tuna': 'tonfisk',
  'salmon': 'lax',
  'cod': 'torsk',
  'halibut': 'hälleflundra',
  'scallops': 'kammusslor',
  'mussels': 'musslor',
  'clams': 'musslor',
  'oysters': 'ostron',
  'crab': 'krabba',
  'lobster': 'hummer',
  'octopus': 'bläckfisk',
  'squid': 'bläckfisk',
  'bacon': 'bacon',
  'ham': 'skinka',
  'sausage': 'korv',
  'pepperoni': 'pepperoni',
  'prosciutto': 'prosciutto',
  'pancetta': 'pancetta',
  'chorizo': 'chorizo',
  'salami': 'salami',
  'bologna': 'bologna',
  'hot dog': 'korv',
  'burger': 'hamburgare',
  'sandwich': 'smörgås',
  'pizza': 'pizza',
  'pasta': 'pasta',
  'spaghetti': 'spaghetti',
  'fettuccine': 'fettuccine',
  'linguine': 'linguine',
  'penne': 'penne',
  'rigatoni': 'rigatoni',
  'lasagna': 'lasagne',
  'ravioli': 'ravioli',
  'gnocchi': 'gnocchi',
  'risotto': 'risotto',
  'paella': 'paella',
  'sushi': 'sushi',
  'sashimi': 'sashimi',
  'ramen': 'ramen',
  'udon': 'udon',
  'soba': 'soba',
  'pho': 'pho',
  'pad thai': 'pad thai',
  'curry': 'curry',
  'tikka masala': 'tikka masala',
  'biryani': 'biryani',
  'naan': 'naan',
  'chapati': 'chapati',
  'tortilla': 'tortilla',
  'taco': 'taco',
  'burrito': 'burrito',
  'quesadilla': 'quesadilla',
  'enchilada': 'enchilada',
  'fajita': 'fajita',
  'guacamole': 'guacamole',
  'salsa': 'salsa',
  'hummus': 'hummus',
  'tzatziki': 'tzatziki',
  'pesto': 'pesto',
  'marinara': 'marinara',
  'alfredo': 'alfredo',
  'bolognese': 'bolognese',
  'carbonara': 'carbonara',
  'puttanesca': 'puttanesca',
  'arrabbiata': 'arrabbiata',
  'aglio e olio': 'aglio e olio',
  'cacio e pepe': 'cacio e pepe',
  'amatriciana': 'amatriciana',
  'gricia': 'gricia',
  'all\'amatriciana': 'all\'amatriciana',
  'alla carbonara': 'alla carbonara',
  'alla puttanesca': 'alla puttanesca',
  'all\'arrabbiata': 'all\'arrabbiata',
  'al pomodoro': 'al pomodoro',
  'al ragù': 'al ragù',
  'al sugo': 'al sugo',
  'in bianco': 'in bianco',
  'in rosso': 'in rosso',
  'al dente': 'al dente',
  'creamy': 'krämig',
  'crispy': 'knaprig',
  'tender': 'mör',
  'juicy': 'saftig',
  'spicy': 'stark',
  'sweet': 'söt',
  'sour': 'sur',
  'bitter': 'bitter',
  'salty': 'salt',
  'umami': 'umami',
  'aromatic': 'aromatisk',
  'fragrant': 'doftande',
  'fresh': 'färsk',
  'dried': 'torkad',
  'canned': 'konserverad',
  'frozen': 'fryst',
  'organic': 'ekologisk',
  'free-range': 'frigående',
  'grass-fed': 'gräsmatad',
  'wild-caught': 'vildfångad',
  'farm-raised': 'uppfödda',
  'sustainable': 'hållbar',
  'local': 'lokal',
  'seasonal': 'säsongsbetonad',
  'traditional': 'traditionell',
  'authentic': 'äkta',
  'homemade': 'hemlagad',
  'artisanal': 'hantverksmässig',
  'gourmet': 'gourmet',
  'premium': 'premium',
  'deluxe': 'deluxe',
  'special': 'speciell',
  'signature': 'signatur',
  'classic': 'klassisk',
  'modern': 'modern',
  'fusion': 'fusion',
  'contemporary': 'samtida',
  'innovative': 'innovativ',
  'creative': 'kreativ',
  'unique': 'unik',
  'exotic': 'exotisk',
  'international': 'internationell',
  'global': 'global',
  'world': 'världs',
  'continental': 'kontinental',
  'regional': 'regional',
  'local': 'lokal',
  'national': 'nationell',
  'ethnic': 'etnisk',
  'cultural': 'kulturell',
  'heritage': 'arv',
  'ancestral': 'förfäder',
  'family': 'familj',
  'grandmother': 'mormor',
  'mother': 'mor',
  'chef': 'kock',
  'restaurant': 'restaurang',
  'cafe': 'kafé',
  'bistro': 'bistro',
  'trattoria': 'trattoria',
  'osteria': 'osteria',
  'taverna': 'taverna',
  'cantina': 'cantina',
  'enoteca': 'enoteca',
  'gelateria': 'gelateria',
  'pasticceria': 'pasticceria',
  'panificio': 'panificio',
  'macelleria': 'macelleria',
  'pescheria': 'pescheria',
  'fruttivendolo': 'fruttivendolo',
  'ortolano': 'ortolano',
  'salumeria': 'salumeria',
  'formaggeria': 'formaggeria',
  'vinaio': 'vinaio',
  'sommelier': 'sommelier',
  'maître d\'': 'maître d\'',
  'waiter': 'servitör',
  'waitress': 'servitris',
  'bartender': 'bartender',
  'barista': 'barista',
  'baker': 'bagare',
  'pastry chef': 'konditor',
  'sous chef': 'souschef',
  'head chef': 'huvudkock',
  'executive chef': 'exekutivkock',
  'chef de cuisine': 'chef de cuisine',
  'chef de partie': 'chef de partie',
  'commis chef': 'commis chef',
  'kitchen porter': 'köksassistent',
  'dishwasher': 'diskare',
  'prep cook': 'förberedare',
  'line cook': 'linjekock',
  'grill cook': 'grillkock',
  'fry cook': 'fritöskock',
  'salad chef': 'salladskock',
  'garde manger': 'garde manger',
  'saucier': 'saucier',
  'poissonnier': 'poissonnier',
  'rotisseur': 'rotisseur',
  'entremetier': 'entremetier',
  'tournant': 'tournant',
  'chef de garde': 'chef de garde',
  'chef de nuit': 'chef de nuit',
  'chef de jour': 'chef de jour',
  'chef de matin': 'chef de matin',
  'chef de soir': 'chef de soir',
  'chef de weekend': 'chef de weekend',
  'chef de vacances': 'chef de vacances',
  'chef de remplacement': 'chef de remplacement',
  'chef de formation': 'chef de formation',
  'chef de stage': 'chef de stage',
  'chef de apprentissage': 'chef de apprentissage',
  'chef de debutant': 'chef de debutant',
  'chef de junior': 'chef de junior',
  'chef de senior': 'chef de senior',
  'chef de expert': 'chef de expert',
  'chef de master': 'chef de master',
  'chef de grand': 'chef de grand',
  'chef de petit': 'chef de petit',
  'chef de nouveau': 'chef de nouveau',
  'chef de ancien': 'chef de ancien',
  'chef de jeune': 'chef de jeune',
  'chef de vieux': 'chef de vieux',
  'chef de moderne': 'chef de moderne',
  'chef de traditionnel': 'chef de traditionnel',
  'chef de classique': 'chef de classique',
  'chef de contemporain': 'chef de contemporain',
  'chef de innovant': 'chef de innovant',
  'chef de creatif': 'chef de creatif',
  'chef de unique': 'chef de unique',
  'chef de special': 'chef de special',
  'chef de exceptionnel': 'chef de exceptionnel',
  'chef de extraordinaire': 'chef de extraordinaire',
  'chef de remarquable': 'chef de remarquable',
  'chef de notable': 'chef de notable',
  'chef de celebre': 'chef de celebre',
  'chef de renomme': 'chef de renomme',
  'chef de repute': 'chef de repute',
  'chef de prestige': 'chef de prestige',
  'chef de renom': 'chef de renom',
  'chef de gloire': 'chef de gloire',
  'chef de honneur': 'chef de honneur',
  'chef de merite': 'chef de merite',
  'chef de distinction': 'chef de distinction',
  'chef de excellence': 'chef de excellence',
  'chef de perfection': 'chef de perfection',
  'chef de ideal': 'chef de ideal',
  'chef de parfait': 'chef de parfait',
  'chef de sublime': 'chef de sublime',
  'chef de magnifique': 'chef de magnifique',
  'chef de splendide': 'chef de splendide',
  'chef de superbe': 'chef de superbe',
  'chef de merveilleux': 'chef de merveilleux',
  'chef de fantastique': 'chef de fantastique',
  'chef de incroyable': 'chef de incroyable',
  'chef de extraordinaire': 'chef de extraordinaire',
  'chef de exceptionnel': 'chef de exceptionnel',
  'chef de remarquable': 'chef de remarquable',
  'chef de notable': 'chef de notable',
  'chef de celebre': 'chef de celebre',
  'chef de renomme': 'chef de renomme',
  'chef de repute': 'chef de repute',
  'chef de prestige': 'chef de prestige',
  'chef de renom': 'chef de renom',
  'chef de gloire': 'chef de gloire',
  'chef de honneur': 'chef de honneur',
  'chef de merite': 'chef de merite',
  'chef de distinction': 'chef de distinction',
  'chef de excellence': 'chef de excellence',
  'chef de perfection': 'chef de perfection',
  'chef de ideal': 'chef de ideal',
  'chef de parfait': 'chef de parfait',
  'chef de sublime': 'chef de sublime',
  'chef de magnifique': 'chef de magnifique',
  'chef de splendide': 'chef de splendide',
  'chef de superbe': 'chef de superbe',
  'chef de merveilleux': 'chef de merveilleux',
  'chef de fantastique': 'chef de fantastique',
  'chef de incroyable': 'chef de incroyable'
};

// Function to translate text
function translateText(text) {
  if (!text) return text;
  
  let translated = text;
  
  // Replace common terms
  Object.entries(translations).forEach(([english, swedish]) => {
    const regex = new RegExp(`\\b${english}\\b`, 'gi');
    translated = translated.replace(regex, swedish);
  });
  
  return translated;
}

// Function to translate a recipe
function translateRecipe(recipe) {
  return {
    ...recipe,
    name: translateText(recipe.name),
    description: translateText(recipe.description),
    ingredientsWithAmounts: recipe.ingredientsWithAmounts.map(item => translateText(item)),
    instructions: recipe.instructions.map(step => translateText(step)),
    difficulty: translations[recipe.difficulty] || recipe.difficulty,
    tags: recipe.tags ? recipe.tags.map(tag => translateText(tag)) : []
  };
}

// Translate all cuisines
Object.entries(enRecipes.cultural).forEach(([cuisine, recipes]) => {
  console.log(`🔄 Translating ${cuisine} recipes...`);
  
  const translatedRecipes = recipes.map(recipe => translateRecipe(recipe));
  svRecipes.cultural[cuisine] = translatedRecipes;
  
  console.log(`   ✅ Translated ${recipes.length} ${cuisine} recipes`);
});

// Write back to Swedish file
fs.writeFileSync('src/locales/sv/recipes.json', JSON.stringify(svRecipes, null, 2));

console.log('');
console.log('🎉 Swedish translation complete!');
console.log('');
console.log('📊 Swedish recipe counts:');
Object.entries(svRecipes.cultural).forEach(([cuisine, recipes]) => {
  console.log(`   ${cuisine}: ${recipes.length} recipes ✅`);
});
