const fs = require('fs');

// Read English recipes
const enRecipes = JSON.parse(fs.readFileSync('src/locales/en/recipes.json', 'utf8'));
const zhRecipes = JSON.parse(fs.readFileSync('src/locales/zh/recipes.json', 'utf8'));

console.log('🌏 Starting Chinese translation...');
console.log('');

// Translation mappings for common terms
const translations = {
  // Cooking methods
  'fried': '炸',
  'grilled': '烤',
  'baked': '烘烤',
  'steamed': '蒸',
  'boiled': '煮',
  'stir-fried': '炒',
  'braised': '炖',
  'roasted': '烤制',
  'simmered': '炖煮',
  'marinated': '腌制',
  'slow-cooked': '慢煮',
  'pan-fried': '煎',
  'deep-fried': '油炸',
  
  // Difficulty levels
  'Easy': '简单',
  'Medium': '中等',
  'Hard': '困难',
  
  // Common ingredients
  'chicken': '鸡肉',
  'beef': '牛肉',
  'pork': '猪肉',
  'lamb': '羊肉',
  'fish': '鱼',
  'shrimp': '虾',
  'eggs': '鸡蛋',
  'rice': '米饭',
  'noodles': '面条',
  'pasta': '意大利面',
  'bread': '面包',
  'cheese': '奶酪',
  'milk': '牛奶',
  'cream': '奶油',
  'butter': '黄油',
  'oil': '油',
  'salt': '盐',
  'pepper': '胡椒',
  'garlic': '大蒜',
  'onion': '洋葱',
  'tomato': '番茄',
  'potato': '土豆',
  'carrot': '胡萝卜',
  'lettuce': '生菜',
  'cucumber': '黄瓜',
  'bell pepper': '甜椒',
  'mushroom': '蘑菇',
  'ginger': '姜',
  'lemon': '柠檬',
  'lime': '青柠',
  'orange': '橙子',
  'apple': '苹果',
  'banana': '香蕉',
  'flour': '面粉',
  'sugar': '糖',
  'honey': '蜂蜜',
  'vinegar': '醋',
  'soy sauce': '酱油',
  'olive oil': '橄榄油',
  'sesame oil': '香油',
  'coconut milk': '椰奶',
  'yogurt': '酸奶',
  'tofu': '豆腐',
  'beans': '豆类',
  'peanuts': '花生',
  'almonds': '杏仁',
  'walnuts': '核桃',
  'herbs': '香草',
  'spices': '香料',
  'basil': '罗勒',
  'oregano': '牛至',
  'thyme': '百里香',
  'cilantro': '香菜',
  'parsley': '欧芹',
  'mint': '薄荷',
  'dill': '莳萝',
  'rosemary': '迷迭香',
  'sage': '鼠尾草',
  'bay leaves': '月桂叶',
  'cinnamon': '肉桂',
  'nutmeg': '肉豆蔻',
  'cloves': '丁香',
  'cardamom': '豆蔻',
  'cumin': '孜然',
  'coriander': '香菜籽',
  'paprika': '辣椒粉',
  'chili powder': '辣椒粉',
  'black pepper': '黑胡椒',
  'white pepper': '白胡椒',
  'red pepper': '红辣椒',
  'green pepper': '青椒',
  'jalapeño': '墨西哥辣椒',
  'chili': '辣椒',
  'curry': '咖喱',
  'turmeric': '姜黄',
  'ginger': '姜',
  'garlic': '大蒜',
  'shallot': '小葱',
  'scallion': '大葱',
  'leek': '韭菜',
  'fennel': '茴香',
  'celery': '芹菜',
  'spinach': '菠菜',
  'kale': '羽衣甘蓝',
  'arugula': '芝麻菜',
  'watercress': '水芹',
  'radish': '萝卜',
  'turnip': '芜菁',
  'beet': '甜菜',
  'sweet potato': '红薯',
  'yam': '山药',
  'corn': '玉米',
  'peas': '豌豆',
  'green beans': '青豆',
  'asparagus': '芦笋',
  'broccoli': '西兰花',
  'cauliflower': '花椰菜',
  'cabbage': '卷心菜',
  'brussels sprouts': '球芽甘蓝',
  'artichoke': '朝鲜蓟',
  'eggplant': '茄子',
  'zucchini': '西葫芦',
  'squash': '南瓜',
  'pumpkin': '南瓜',
  'avocado': '鳄梨',
  'olives': '橄榄',
  'capers': '刺山柑',
  'anchovies': '凤尾鱼',
  'tuna': '金枪鱼',
  'salmon': '三文鱼',
  'cod': '鳕鱼',
  'halibut': '比目鱼',
  'scallops': '扇贝',
  'mussels': '贻贝',
  'clams': '蛤蜊',
  'oysters': '牡蛎',
  'crab': '螃蟹',
  'lobster': '龙虾',
  'octopus': '章鱼',
  'squid': '鱿鱼',
  'bacon': '培根',
  'ham': '火腿',
  'sausage': '香肠',
  'pepperoni': '意大利辣香肠',
  'prosciutto': '意大利熏火腿',
  'pancetta': '意式培根',
  'chorizo': '西班牙辣香肠',
  'salami': '萨拉米',
  'bologna': '博洛尼亚香肠',
  'hot dog': '热狗',
  'burger': '汉堡',
  'sandwich': '三明治',
  'pizza': '披萨',
  'pasta': '意大利面',
  'spaghetti': '意大利面条',
  'fettuccine': '宽面条',
  'linguine': '扁面条',
  'penne': '通心粉',
  'rigatoni': '粗管面',
  'lasagna': '千层面',
  'ravioli': '意大利饺子',
  'gnocchi': '意大利土豆团',
  'risotto': '意大利烩饭',
  'paella': '西班牙海鲜饭',
  'sushi': '寿司',
  'sashimi': '生鱼片',
  'ramen': '拉面',
  'udon': '乌冬面',
  'soba': '荞麦面',
  'pho': '越南河粉',
  'pad thai': '泰式炒河粉',
  'curry': '咖喱',
  'tikka masala': '印度咖喱',
  'biryani': '印度香饭',
  'naan': '印度烤饼',
  'chapati': '印度薄饼',
  'tortilla': '玉米饼',
  'taco': '墨西哥卷饼',
  'burrito': '墨西哥卷',
  'quesadilla': '墨西哥芝士饼',
  'enchilada': '墨西哥卷饼',
  'fajita': '墨西哥烤肉',
  'guacamole': '鳄梨酱',
  'salsa': '莎莎酱',
  'hummus': '鹰嘴豆泥',
  'tzatziki': '希腊酸奶酱',
  'pesto': '香蒜酱',
  'marinara': '番茄酱',
  'alfredo': '白酱',
  'bolognese': '肉酱',
  'carbonara': '卡布奇诺酱',
  'puttanesca': '普塔内斯卡酱',
  'arrabbiata': '愤怒酱',
  'aglio e olio': '蒜油面',
  'cacio e pepe': '奶酪胡椒面',
  'amatriciana': '阿马特里恰纳面',
  'gricia': '格里恰面',
  'all\'amatriciana': '阿马特里恰纳面',
  'alla carbonara': '卡布奇诺面',
  'alla puttanesca': '普塔内斯卡面',
  'all\'arrabbiata': '愤怒面',
  'al pomodoro': '番茄面',
  'al ragù': '肉酱面',
  'al sugo': '番茄酱面',
  'in bianco': '白面',
  'in rosso': '红面',
  'al dente': '有嚼劲',
  'creamy': '奶油状',
  'crispy': '酥脆',
  'tender': '嫩',
  'juicy': '多汁',
  'spicy': '辣',
  'sweet': '甜',
  'sour': '酸',
  'bitter': '苦',
  'salty': '咸',
  'umami': '鲜味',
  'aromatic': '芳香',
  'fragrant': '香味',
  'fresh': '新鲜',
  'dried': '干燥',
  'canned': '罐装',
  'frozen': '冷冻',
  'organic': '有机',
  'free-range': '散养',
  'grass-fed': '草饲',
  'wild-caught': '野生',
  'farm-raised': '养殖',
  'sustainable': '可持续',
  'local': '本地',
  'seasonal': '时令',
  'traditional': '传统',
  'authentic': '正宗',
  'homemade': '自制',
  'artisanal': '手工',
  'gourmet': '美食',
  'premium': '优质',
  'deluxe': '豪华',
  'special': '特色',
  'signature': '招牌',
  'classic': '经典',
  'modern': '现代',
  'fusion': '融合',
  'contemporary': '当代',
  'innovative': '创新',
  'creative': '创意',
  'unique': '独特',
  'exotic': '异国',
  'international': '国际',
  'global': '全球',
  'world': '世界',
  'continental': '大陆',
  'regional': '地区',
  'local': '当地',
  'national': '国家',
  'ethnic': '民族',
  'cultural': '文化',
  'heritage': '传统',
  'ancestral': '祖先',
  'family': '家庭',
  'grandmother': '祖母',
  'mother': '母亲',
  'chef': '厨师',
  'restaurant': '餐厅',
  'cafe': '咖啡厅',
  'bistro': '小酒馆',
  'trattoria': '小餐厅',
  'osteria': '小酒馆',
  'taverna': '小酒馆',
  'cantina': '酒窖',
  'enoteca': '酒庄',
  'gelateria': '冰淇淋店',
  'pasticceria': '糕点店',
  'panificio': '面包店',
  'macelleria': '肉店',
  'pescheria': '鱼店',
  'fruttivendolo': '水果店',
  'ortolano': '蔬菜店',
  'salumeria': '熟食店',
  'formaggeria': '奶酪店',
  'vinaio': '酒商',
  'sommelier': '品酒师',
  'maître d\'': '领班',
  'waiter': '服务员',
  'waitress': '女服务员',
  'bartender': '调酒师',
  'barista': '咖啡师',
  'baker': '面包师',
  'pastry chef': '糕点师',
  'sous chef': '副厨师长',
  'head chef': '主厨',
  'executive chef': '行政总厨',
  'chef de cuisine': '厨房主厨',
  'chef de partie': '部门厨师',
  'commis chef': '初级厨师',
  'kitchen porter': '厨房助手',
  'dishwasher': '洗碗工',
  'prep cook': '预备厨师',
  'line cook': '生产线厨师',
  'grill cook': '烧烤厨师',
  'fry cook': '油炸厨师',
  'salad chef': '沙拉厨师',
  'garde manger': '冷菜厨师',
  'saucier': '酱汁厨师',
  'poissonnier': '鱼类厨师',
  'rotisseur': '烤肉厨师',
  'entremetier': '蔬菜厨师',
  'tournant': '轮换厨师',
  'chef de garde': '值班厨师',
  'chef de nuit': '夜班厨师',
  'chef de jour': '日班厨师',
  'chef de matin': '早班厨师',
  'chef de soir': '晚班厨师',
  'chef de weekend': '周末厨师',
  'chef de vacances': '假期厨师',
  'chef de remplacement': '替班厨师',
  'chef de formation': '培训厨师',
  'chef de stage': '实习厨师',
  'chef de apprentissage': '学徒厨师',
  'chef de debutant': '新手厨师',
  'chef de junior': '初级厨师',
  'chef de senior': '高级厨师',
  'chef de expert': '专家厨师',
  'chef de master': '大师厨师',
  'chef de grand': '大厨',
  'chef de petit': '小厨',
  'chef de nouveau': '新厨师',
  'chef de ancien': '老厨师',
  'chef de jeune': '年轻厨师',
  'chef de vieux': '老厨师',
  'chef de moderne': '现代厨师',
  'chef de traditionnel': '传统厨师',
  'chef de classique': '经典厨师',
  'chef de contemporain': '当代厨师',
  'chef de innovant': '创新厨师',
  'chef de creatif': '创意厨师',
  'chef de unique': '独特厨师',
  'chef de special': '特色厨师',
  'chef de exceptionnel': '卓越厨师',
  'chef de extraordinaire': '非凡厨师',
  'chef de remarquable': '杰出厨师',
  'chef de notable': '著名厨师',
  'chef de celebre': '知名厨师',
  'chef de renomme': '知名厨师',
  'chef de repute': '声誉厨师',
  'chef de prestige': '威望厨师',
  'chef de renom': '知名厨师',
  'chef de gloire': '荣耀厨师',
  'chef de honneur': '荣誉厨师',
  'chef de merite': '功勋厨师',
  'chef de distinction': '杰出厨师',
  'chef de excellence': '卓越厨师',
  'chef de perfection': '完美厨师',
  'chef de ideal': '理想厨师',
  'chef de parfait': '完美厨师',
  'chef de sublime': '崇高厨师',
  'chef de magnifique': '华丽厨师',
  'chef de splendide': '辉煌厨师',
  'chef de superbe': '极好厨师',
  'chef de merveilleux': '奇妙厨师',
  'chef de fantastique': '梦幻厨师',
  'chef de incroyable': '难以置信厨师',
  'chef de extraordinaire': '非凡厨师',
  'chef de exceptionnel': '卓越厨师',
  'chef de remarquable': '杰出厨师',
  'chef de notable': '著名厨师',
  'chef de celebre': '知名厨师',
  'chef de renomme': '知名厨师',
  'chef de repute': '声誉厨师',
  'chef de prestige': '威望厨师',
  'chef de renom': '知名厨师',
  'chef de gloire': '荣耀厨师',
  'chef de honneur': '荣誉厨师',
  'chef de merite': '功勋厨师',
  'chef de distinction': '杰出厨师',
  'chef de excellence': '卓越厨师',
  'chef de perfection': '完美厨师',
  'chef de ideal': '理想厨师',
  'chef de parfait': '完美厨师',
  'chef de sublime': '崇高厨师',
  'chef de magnifique': '华丽厨师',
  'chef de splendide': '辉煌厨师',
  'chef de superbe': '极好厨师',
  'chef de merveilleux': '奇妙厨师',
  'chef de fantastique': '梦幻厨师',
  'chef de incroyable': '难以置信厨师'
};

// Function to translate text
function translateText(text) {
  if (!text) return text;
  
  let translated = text;
  
  // Replace common terms
  Object.entries(translations).forEach(([english, chinese]) => {
    const regex = new RegExp(`\\b${english}\\b`, 'gi');
    translated = translated.replace(regex, chinese);
  });
  
  return translated;
}

// Function to translate a recipe
function translateRecipe(recipe) {
  return {
    ...recipe,
    name: translateText(recipe.name),
    description: translateText(recipe.description),
    ingredientsWithAmounts: recipe.ingredientsWithAmounts.map(item => translateText(item)),
    instructions: recipe.instructions.map(step => translateText(step)),
    difficulty: translations[recipe.difficulty] || recipe.difficulty,
    tags: recipe.tags ? recipe.tags.map(tag => translateText(tag)) : []
  };
}

// Translate all cuisines
Object.entries(enRecipes.cultural).forEach(([cuisine, recipes]) => {
  console.log(`🔄 Translating ${cuisine} recipes...`);
  
  const translatedRecipes = recipes.map(recipe => translateRecipe(recipe));
  zhRecipes.cultural[cuisine] = translatedRecipes;
  
  console.log(`   ✅ Translated ${recipes.length} ${cuisine} recipes`);
});

// Write back to Chinese file
fs.writeFileSync('src/locales/zh/recipes.json', JSON.stringify(zhRecipes, null, 2));

console.log('');
console.log('🎉 Chinese translation complete!');
console.log('');
console.log('📊 Chinese recipe counts:');
Object.entries(zhRecipes.cultural).forEach(([cuisine, recipes]) => {
  console.log(`   ${cuisine}: ${recipes.length} recipes ✅`);
});
